//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TweetBeer.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TweetBeerContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TweetBeerContainer object using the connection string found in the 'TweetBeerContainer' section of the application configuration file.
        /// </summary>
        public TweetBeerContainer() : base("name=TweetBeerContainer", "TweetBeerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TweetBeerContainer object.
        /// </summary>
        public TweetBeerContainer(string connectionString) : base(connectionString, "TweetBeerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TweetBeerContainer object.
        /// </summary>
        public TweetBeerContainer(EntityConnection connection) : base(connection, "TweetBeerContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Beer> Beer
        {
            get
            {
                if ((_Beer == null))
                {
                    _Beer = base.CreateObjectSet<Beer>("Beer");
                }
                return _Beer;
            }
        }
        private ObjectSet<Beer> _Beer;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Beer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBeer(Beer beer)
        {
            base.AddObject("Beer", beer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TweetBeer", Name="Beer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(StoutBeer))]
    [KnownTypeAttribute(typeof(PremiumBeer))]
    public abstract partial class Beer : EntityObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Double _Weight;
        partial void OnWeightChanging(global::System.Double value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double InitialWeight
        {
            get
            {
                return _InitialWeight;
            }
            set
            {
                OnInitialWeightChanging(value);
                ReportPropertyChanging("InitialWeight");
                _InitialWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InitialWeight");
                OnInitialWeightChanged();
            }
        }
        private global::System.Double _InitialWeight;
        partial void OnInitialWeightChanging(global::System.Double value);
        partial void OnInitialWeightChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TweetBeer", Name="PremiumBeer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PremiumBeer : Beer
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PremiumBeer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="initialWeight">Initial value of the InitialWeight property.</param>
        public static PremiumBeer CreatePremiumBeer(global::System.Int64 id, global::System.String name, global::System.String country, global::System.Double weight, global::System.Double initialWeight)
        {
            PremiumBeer premiumBeer = new PremiumBeer();
            premiumBeer.Id = id;
            premiumBeer.Name = name;
            premiumBeer.Country = country;
            premiumBeer.Weight = weight;
            premiumBeer.InitialWeight = initialWeight;
            return premiumBeer;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TweetBeer", Name="StoutBeer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StoutBeer : Beer
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StoutBeer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="initialWeight">Initial value of the InitialWeight property.</param>
        public static StoutBeer CreateStoutBeer(global::System.Int64 id, global::System.String name, global::System.String country, global::System.Double weight, global::System.Double initialWeight)
        {
            StoutBeer stoutBeer = new StoutBeer();
            stoutBeer.Id = id;
            stoutBeer.Name = name;
            stoutBeer.Country = country;
            stoutBeer.Weight = weight;
            stoutBeer.InitialWeight = initialWeight;
            return stoutBeer;
        }

        #endregion
    
    }

    #endregion
    
}
