//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TweetBeerModel", "FK_PremiumBeer_inherits_Beer", "Beer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CSharpDynamicData.Web.Models.Beer), "Beer_PremiumBeer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSharpDynamicData.Web.Models.Beer_PremiumBeer), true)]
[assembly: EdmRelationshipAttribute("TweetBeerModel", "FK_StoutBeer_inherits_Beer", "Beer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CSharpDynamicData.Web.Models.Beer), "Beer_StoutBeer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CSharpDynamicData.Web.Models.Beer_StoutBeer), true)]

#endregion

namespace CSharpDynamicData.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TweetBeerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TweetBeerEntities object using the connection string found in the 'TweetBeerEntities' section of the application configuration file.
        /// </summary>
        public TweetBeerEntities() : base("name=TweetBeerEntities", "TweetBeerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TweetBeerEntities object.
        /// </summary>
        public TweetBeerEntities(string connectionString) : base(connectionString, "TweetBeerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TweetBeerEntities object.
        /// </summary>
        public TweetBeerEntities(EntityConnection connection) : base(connection, "TweetBeerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Beer> Beer
        {
            get
            {
                if ((_Beer == null))
                {
                    _Beer = base.CreateObjectSet<Beer>("Beer");
                }
                return _Beer;
            }
        }
        private ObjectSet<Beer> _Beer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Beer_PremiumBeer> Beer_PremiumBeer
        {
            get
            {
                if ((_Beer_PremiumBeer == null))
                {
                    _Beer_PremiumBeer = base.CreateObjectSet<Beer_PremiumBeer>("Beer_PremiumBeer");
                }
                return _Beer_PremiumBeer;
            }
        }
        private ObjectSet<Beer_PremiumBeer> _Beer_PremiumBeer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Beer_StoutBeer> Beer_StoutBeer
        {
            get
            {
                if ((_Beer_StoutBeer == null))
                {
                    _Beer_StoutBeer = base.CreateObjectSet<Beer_StoutBeer>("Beer_StoutBeer");
                }
                return _Beer_StoutBeer;
            }
        }
        private ObjectSet<Beer_StoutBeer> _Beer_StoutBeer;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Beer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBeer(Beer beer)
        {
            base.AddObject("Beer", beer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Beer_PremiumBeer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBeer_PremiumBeer(Beer_PremiumBeer beer_PremiumBeer)
        {
            base.AddObject("Beer_PremiumBeer", beer_PremiumBeer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Beer_StoutBeer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBeer_StoutBeer(Beer_StoutBeer beer_StoutBeer)
        {
            base.AddObject("Beer_StoutBeer", beer_StoutBeer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TweetBeerModel", Name="Beer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]    
    public partial class Beer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Beer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="weight">Initial value of the Weight property.</param>
        /// <param name="initialWeight">Initial value of the InitialWeight property.</param>
        public static Beer CreateBeer(global::System.Int64 id, global::System.String name, global::System.String country, global::System.Double weight, global::System.Double initialWeight)
        {
            Beer beer = new Beer();
            beer.Id = id;
            beer.Name = name;
            beer.Country = country;
            beer.Weight = weight;
            beer.InitialWeight = initialWeight;
            return beer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.Double _Weight;
        partial void OnWeightChanging(global::System.Double value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double InitialWeight
        {
            get
            {
                return _InitialWeight;
            }
            set
            {
                OnInitialWeightChanging(value);
                ReportPropertyChanging("InitialWeight");
                _InitialWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InitialWeight");
                OnInitialWeightChanged();
            }
        }
        private global::System.Double _InitialWeight;
        partial void OnInitialWeightChanging(global::System.Double value);
        partial void OnInitialWeightChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TweetBeerModel", "FK_PremiumBeer_inherits_Beer", "Beer_PremiumBeer")]
        public Beer_PremiumBeer Beer_PremiumBeer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer_PremiumBeer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer_PremiumBeer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer_PremiumBeer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer_PremiumBeer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Beer_PremiumBeer> Beer_PremiumBeerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer_PremiumBeer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer_PremiumBeer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Beer_PremiumBeer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer_PremiumBeer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TweetBeerModel", "FK_StoutBeer_inherits_Beer", "Beer_StoutBeer")]
        public Beer_StoutBeer Beer_StoutBeer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer_StoutBeer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer_StoutBeer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer_StoutBeer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer_StoutBeer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Beer_StoutBeer> Beer_StoutBeerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer_StoutBeer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer_StoutBeer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Beer_StoutBeer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer_StoutBeer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TweetBeerModel", Name="Beer_PremiumBeer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Beer_PremiumBeer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Beer_PremiumBeer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Beer_PremiumBeer CreateBeer_PremiumBeer(global::System.Int64 id)
        {
            Beer_PremiumBeer beer_PremiumBeer = new Beer_PremiumBeer();
            beer_PremiumBeer.Id = id;
            return beer_PremiumBeer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TweetBeerModel", "FK_PremiumBeer_inherits_Beer", "Beer")]
        public Beer Beer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Beer> BeerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Beer>("TweetBeerModel.FK_PremiumBeer_inherits_Beer", "Beer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TweetBeerModel", Name="Beer_StoutBeer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Beer_StoutBeer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Beer_StoutBeer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Beer_StoutBeer CreateBeer_StoutBeer(global::System.Int64 id)
        {
            Beer_StoutBeer beer_StoutBeer = new Beer_StoutBeer();
            beer_StoutBeer.Id = id;
            return beer_StoutBeer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TweetBeerModel", "FK_StoutBeer_inherits_Beer", "Beer")]
        public Beer Beer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Beer> BeerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Beer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Beer>("TweetBeerModel.FK_StoutBeer_inherits_Beer", "Beer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
